apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: metrics-app-monitor
  labels:
    app: metrics-app
spec:
  selector:
    matchLabels:
      app: metrics-app
  podMetricsEndpoints:
  - port: web
